[package]
name = "weather-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
chrono-tz = "0.10.4"
reqwest = { version = "0.12.23", features = ["json"] }
serde = "1.0.225"
tokio = { version = "1.47.1", features = ["full"] }
